### ISSUE TITLE
[suggestion/request] example configurations

### ISSUE THREAD

**Issue by majijn** [TheIllusiveC4/Champions#1]
I just downloaded the mod and there doesnt seem to be any explanation as to how each part of the config works, how im supposed to add mobs, multiple mobs per rank ; etc.
is there an explanation somewhere that im just missing? if there isnt, would it be possible for one to be added to the configs or to this git's wiki?

**Comment by TheIllusiveC4** [comment]
Are you talking about the `champions.cfg` file or the champions folder with the json files? The former has a description with each setting explaining what it does. The latter does not have an explanation, that's something that I'm working on.

**Comment by majijn** [comment]
mostly the jsons , but in champions.cfg the name needed for mobs is their modname:mobname? or can vanilla mobs get away with just being their mobname? seems to be the case given I added "creeper"
and it seems to be working, but Ithought to ask just in case I've just been very lucky,

LOVING the mod btw, great work, makes mobs scary which is exactly the mood I wanted for my pack

I'm looking forward to being able to see what each setting changes! thank you so much for the work you're putting on this

**Comment by TheIllusiveC4** [comment]
For your specific question, it's like you suggested. You'll usually need modid:name, but you can just use the name if it's a vanilla mob and should turn out alright.

I'm definitely gonna add some explanations about all the json configurations soon.

Thanks, glad you're enjoying the mod so far.

**Comment by TheIllusiveC4** [comment]
I've written up some documentation on the json configuration files. You can find them on the GitHub wiki's sidebar: https://github.com/TheIllusiveC4/Champions/wiki
