### ISSUE TITLE
Crash on attacking a reflective champion, need help deciphering crash report

### ISSUE THREAD

**Issue by Jackiecrazy** [TheIllusiveC4/Champions#101]
#### Versions (Be specific, do not write "latest"):
* Champions: 2.0.1.8
* Forge: 36.2.22

#### Observed Behavior:
I am entirely uncertain why this happens. It doesn't happen on another world which is nearly identical. Reverting the mods that changed between the two worlds did not fix it, neither did updating (or downgrading) the graphics driver and changing java/forge versions. I did perform a full system update just a while ago, so that might have been it. The crash happens upon attacking a champion with the reflective affix. It does not happen in isolation; I need some help in deciphering the crash report, then I can hopefully resolve this myself.
#### Expected Behavior:
The game should not crash.
#### Steps to Reproduce:
1. Install Order of All Creation: Relic Hunters
2. Attack a reflective champion
3. Observe crash. I know installing an entire modpack to test something isn't reasonable to ask, so I'm just asking for help in reading the report. 
...

Crash Log: [gist](https://gist.github.com/Jackiecrazy/10909257902442fd9aca34887a2298bd).

**Comment by TheIllusiveC4** [comment]
I've never seen this error before, and Champions is not in the stacktrace nor does it happen in isolation as you stated so I'm closing this issue in the context of being part of the issue tracker for this repository.

As far as helping you read the report, I did some brief research around to see if I could figure out anything helpful. The most that I can tell is that it has to do with classloading errors, likely from an unidentified mod that is trying to access a class that it hasn't properly loaded for some reason. I know that's kinda vague, but I can't tell much more than that.
