### ISSUE TITLE
Constantly getting "stack underflow" error  in chat whenever I look at an elite mob

### ISSUE THREAD

**Issue by JetpackRescue** [TheIllusiveC4/Champions#102]
using bsl shaders on Forge
1.16.5

OpenGL error: 1284 (Stack Underflow)

**Comment by TheIllusiveC4** [comment]
Although this was reported first, I'll be closing this one in favor of this since it has more information and is likely a similar cause:
https://github.com/TheIllusiveC4/Champions/issues/108
