### ISSUE TITLE
(1.12.2) conflict with the legend of herobrine mod

### ISSUE THREAD

**Issue by rebarakuk** [TheIllusiveC4/Champions#105]
#### Versions (Be specific, do not write "latest"):
Forge Version: 14.23.5.2860
the legend of herobrine Mod Version: 0.5.4
champions mod version: 1.0.11.10

#### Steps to Reproduce:
1. time set to night
2. monsters fighting each other

Crash Log: Please use a paste site like [gist](https://gist.github.com/).
https://gist.github.com/rebarakuk/ff3f6cfc7fd3f84ef88a9613d21003c1

**Comment by TheIllusiveC4** [comment]
This is not something I can fix in Champions. The Legend of Herobrine mod is not checking that the damage source is an instance of `EntityLivingBase` before casting it, which leads to the crash in your report.
