### ISSUE TITLE
[1.18.2] Server crash startup with brutal bosses

### ISSUE THREAD

**Issue by BugmanBugman** [TheIllusiveC4/Champions#111]
-->
#### Versions (Be specific, do not write "latest"):
* Champions: 2-2.1.2.0
* Forge: 40.0.19
brutal bosses: https://www.curseforge.com/minecraft/mc-mods/brutal-bosses-dungeon

#### Observed Behavior:
crash on server startup

#### Steps to Reproduce:
1. start champions on a server with brutal bosses
2. then it crashes
3.
4.
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).
[crash-2022-03-19_14.06.29-server.txt](https://github.com/TheIllusiveC4/Champions/files/8309933/crash-2022-03-19_14.06.29-server.txt)

**Comment by TheIllusiveC4** [comment]
Oh, interesting. I didn't know a mod already had integration with the 1.18.x version of Champions. This is a pretty easy fix.
