### ISSUE TITLE
Missing Translation for "death.attack.cinderBullet"

### ISSUE THREAD

**Issue by VanyaBaou** [TheIllusiveC4/Champions#112]
#### Versions (Be specific, do not write "latest"):
* Champions: champions-forge-1.16.5-2.0.1.9
* Forge: 1.16.5-forge-36.2.23

#### Observed Behavior:
dying to impact of Enkindling bullet
death message being unlocalized text "death.attack.cinderBullet"

#### Expected Behavior:
localized death message

#### Steps to Reproduce:
1. die to impact of enkindling projectile

**Comment by VanyaBaou** [comment]
uh is the fix going to be put in 1.16 as well? didnt even know it was in 1.18

**Comment by TheIllusiveC4** [comment]
Whoops, I thought I did update 1.16 as well. Give me a moment and I'll update it.
