### ISSUE TITLE
Champions mod causing deadlock where world stops ticking but wouldn't crash. fixed after the mod was removed

### ISSUE THREAD

**Issue by RAIMBOWFISH** [TheIllusiveC4/Champions#121]
I made my own mod pack with the following mods:
AE2 Things

AIOT Botania

Additional Additions

Advanced Chimneys

Advanced Hook Launchers

Advent of Ascension

Alex's Mobs

Amplified Nether

Apotheosis

Applied Botanics

Applied Energistics 2

Applied Mekanistics

Aquaculture 2

Architectury

Ars Nouveau

AutoRegLib

Awesome Dungeon

Awesome Dungeon End Addition

Awesome Dungeon Nether Addition

Awesome Dungeon Ocean Addition

Backpacked

Ballistix

Balm

Basic Nether Ores

Beyond Earth

Biomes O' Plenty

Blue Skies

Botania

Breaking Bad Meth Mod

Building Gadgets

Caelus API

Cataclysm Mod

Catalogue

Cave Rats

Champions

Chargin Gadgets

Citadel

Clumps

Comforts

Compressium

Configured

ConnectedTexturesMod

Controlling

CraftTweaker

Create

Creatures from the lush caves

Creeper Overhaul

Cucumber Library

Curios API

Deep Resonance

Dimensional Paintings

Domestication Innovation

Domum Ornamentum

Druidcraft Regrown

DungeonCrawl

Dynamic Electricity

Ecologics

Electrodynamics

Enhanced Celestials

Enhanced Farming

Enlightened End

Exotic Birds

Extreme Reactors

Feature NBT Deadlock

Flywheel

Forbidden and Arcanus

ForgeEndertech

Framework

Friends and Foes

GeckoLib

Global XP

GreaterEye of ender

Guard Villagers

Guns without Roses

HT's Treechop

HT's Treeplant

Hyle

Illagers Wear Armor

Immersive Engineering

Improved Mobs Mod

Incendium

InsaneLib

Iron Jetpacks

JEI Tweaker

Jade

JEI

JER

Large Ore Deposits

Lava Monster

Let Sleeping Dogs Lie

LibX

Library Ferret

Lootr

Mahou Tsukai

Many More Ores

McJtyLib

Measurements

Meet Your Fight

Mekanism

Mekanism: Additions

Mekanism: Generators

Mekanism: Tools

MineColonies

Minecraft Comes Alive

More Axolotyl Variants

More Minecarts

More Ore Stones

Mounted Pearl

MrCrayFish's Gun Mod

Multi-Piston

Mutant Wolf

Mystical Agriculture

Mythic Botany

Nuclear Science

Occultism

Oh The Biomes You'll Go

Paintings ++

Panthalassa

Paraglider

Patchouli

Piglin Expansion

Placebo

Plus The End

Pollution of the Realms

Producutive Bees

Progressive Bosses

Puzzles Lib

Quark

RFToolsBase

RFToolsBuilder

RFToolsControl

RFToolsDimensions

RFToolsPower

RFToolsStorage

Realistic Horse Genetics

Repurposed Structures

Scaling Health

Scarecrows' Territory

Secret Rooms 6

Shutup Experimental Settings!

SignTastic

Silent Gear

Silent Lib

Silent's Gems: Base

SlimyBoyos

Structure Gel API

Structurize

SuperMartijn642's Config Lib

SuperMartijn642's Core Lib

Tenshilib

Terrablender

Terralith

The Bumblezone

The Conjurer

The Graveyard

The King of the Village

The One Probe

The Undergarden

Tiny Skeletons

To the Bat Poles!

Token Enchanter

Torchmaster

TrapCraft

UI Library Mod

Ultimate Car Mod

Ultimate Plane Mod

Unearthed

Valhelsia Core

Valhelsia Structures

Waila (Jade)

Waystones

When Dugeons Arise

Xaero's Minimap

YUNG's API

YUNG's Better Dungeons

YUNG's Better Mineshaft

YUNG's Better Stronghold

YUNG's Brdiges

YUNG's Extras

You Died

ZYCraft

Zero CORE 2

Brutalbosses mod

dragonfight mod

ChromatoCreeper

It would sometimes get stuck while preparing spawn chunks. If the world did manage to load it would work until the world attempted to load a new chunk, at which point the world would stop ticking. It would never crash and give me a crash report. This was resolved when I removed Champions and Scaling health mods.

**Comment by TheIllusiveC4** [comment]
You'll have to give me either the `latest.log` or `debug.log` file from the time that it deadlocked, otherwise I have no information about what could've caused it.

Also, please list out your Champions and Forge version numbers at the very least.

**Comment by zGh0stY** [comment]
It's caused by Scaling Health, had the same issue and removed the mods one by one

**Comment by SergGrey** [comment]
> You'll have to give me either the `latest.log` or `debug.log` file from the time that it deadlocked, otherwise I have no information about what could've caused it.
> 
> Also, please list out your Champions and Forge version numbers at the very least.

Hello, I faced the same problem.
champions-forge-1.18.2-2.1.5.4.jar
Forge - 40.1.20
[debug.log](https://github.com/TheIllusiveC4/Champions/files/8781618/debug.log)
[latest.log](https://github.com/TheIllusiveC4/Champions/files/8781620/latest.log)
[crash-2022-05-26_19.34.18-server.txt](https://github.com/TheIllusiveC4/Champions/files/8786457/crash-2022-05-26_19.34.18-server.txt)
