### ISSUE TITLE
Crash on creating a new world.

### ISSUE THREAD

**Issue by Reshy** [TheIllusiveC4/Champions#122]
#### Versions (Be specific, do not write "latest"):
* Champions:  champions-forge-1.18.2-2.1.5.4.jar
* Forge:  40.1.15

#### Observed Behavior:
Game crashed upon creating a new world.

#### Expected Behavior:
Game shouldn't crash upon creating a new world.

#### Steps to Reproduce:
Attempting to create a world.

Crash Log: https://pastebin.com/gLDwFrnV

**Comment by TheIllusiveC4** [comment]
Did you change the ranks config at all? Can you share your `champions-ranks.toml` file from your `serverconfig` folder?

**Comment by Reshy** [comment]
[[ranks]]
  tier = 0
  numAffixes = 0
  defaultColor = 0xffffff
  chance = 1.0
  growthFactor = 0
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 1
  numAffixes = 1
  defaultColor = 0xffff00
  chance = 0.05
  growthFactor = 1
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 2
  numAffixes = 2
  defaultColor = 0xff9900
  chance = 0.2
  growthFactor = 4
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 3
  numAffixes = 3
  defaultColor = 0x66ffff
  chance = 0.2
  growthFactor = 9
  effects = []
  presetAffixes = []
[[ranks]]
  tier = 4
  numAffixes = 4
  defaultColor = 0xcc33ff
  chance = 0.2
  growthFactor = 16
  effects = []
  presetAffixes = []
