### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Kasia1403** [TheIllusiveC4/Champions#123]
Is it from Your mod ?

![2022-05-08_20 06 09](https://user-images.githubusercontent.com/54236098/169691378-9978b02d-d4d7-447d-b494-c28e699d37b4.png)

This structure spawner spawns unlimited number of mobs adnd lags game very fast. I don't like this, but I don't know from which mod it is and how to disable it.

**Comment by TheIllusiveC4** [comment]
No, Champions has no world generation features.
