### ISSUE TITLE
[1.18.2] Champions HUD stops updating after the player dies

### ISSUE THREAD

**Issue by java-jambalaya** [TheIllusiveC4/Champions#129]
#### Versions:
* Champions: 2.1.5.6 (champions-forge-1.18.2-2.1.5.6.jar)
* Forge: 40.1.68

#### Observed Behavior:
Upon the player dying, the champions HUD stops updating for all champions currently rendered for that player.
Their health bar stops showing their actual health value, and instead shows the amount from the time at which the player had died.
The champion can still be killed in this state, it is just a visual bug.

#### Expected Behavior:
Upon the player dying, the champions HUD continues to update to show their current health value.

#### Steps to Reproduce:
1. Summon or find a Champion (I used '/champions summon minecraft:husk 1').
2. (optional: damage it, the health bar will update).
3. Die somehow (or run '/kill').
4. Respawn and find the Champion.
5. Damage it & notice the health bar no longer updates.

**Comment by java-jambalaya** [comment]
Additionally, the effects from champions in this state (such as ones with the 'plagued' affix) will also remain in the location/state they were in when the player died. In the case of 'plagued', a poison cloud is left where the champion was when the player died, however this cloud does nothing, and the functional poison cloud is invisible and still around that champion.

**Comment by java-jambalaya** [comment]
Furthermore, the particle effects and HUD of champions in this state will become **completely unrendered** if the player pauses the game for a time (I found 10 seconds to be enough to replicate), and they will only show again if the player relogs or respawns, however this still does not cause the health bar to update and show the correct value.

**Comment by TheIllusiveC4** [comment]
Are you able to reproduce this with _just_ Champions installed?

**Comment by java-jambalaya** [comment]
Yes, I can reproduce this on a 1.18.2 profile with forge-40.1.68, and the only mod installed being champions-forge-1.18.2-2.1.5.6.jar.
I've kept all settings and configs as default too in case they could've been the cause.

**Comment by java-jambalaya** [comment]
Hi, just in case this has been forgotten or is difficult to replicate, here's exactly what I did to get this to happen using **just** the Champions mod (1.18.2-2.1.5.6.jar) and Forge 40.1.73, with no other mods installed:

- Create new world (creative mode, cheats on, normal difficulty)
- Dig a 2 deep hole, go in it, and run `/champions summon minecraft:husk 1 arctic`
- Punch it, noticing its health bar drop slightly
- Run `/kill`
- Respawn and go to the champion
- Punch it, noticing its health bar does not update visually anymore **(bug 1)**
- Look away from the champion
- Press ESC to pause the game and keep it paused for at least 10-20 seconds
- Look back at the champion and its effects and health bar no longer show **(bug 2)**

Bug 1 can only be "fixed" by re-logging.
Bug 2 can be "fixed" by dying or re-logging.

Hope this helps.

**Comment by TheIllusiveC4** [comment]
Don't worry, I haven't forgotten and I won't forget as long as this issue remains open. I just haven't had time to fix this quite yet. I have replicated it though and I know what the issue is, the fix is just going to be a little tricky.
