### ISSUE TITLE
[1.18.2] Feature Request: Gamestage support

### ISSUE THREAD

**Issue by Saereth** [TheIllusiveC4/Champions#135]
Is game stage support for 1.18.2 planned at some point, or would you possibly accept a PR for it? I'd love to include the mod in one of our upcoming ftb packs, but currently players are getting spanked hard if a legendary or epic tier mob spawns, so being able to stage that is pretty important, especially for a hardcore optional pack.

**Comment by Raidobw2** [comment]
Facing a similar issue with https://github.com/FTBTeam/FTB-Modpack-Issues/issues/1188, this would be a good feature to have built in I agree! :o

**Comment by TheIllusiveC4** [comment]
I'm planning to add this and some additional features to help gate progression in the next Champions update.

**Comment by Raidobw2** [comment]
Thank you very much for this feature! :)
