### ISSUE TITLE
[1.16.5] /summon entities dont get all stats from ranks config

### ISSUE THREAD

**Issue by MasterSloth1** [TheIllusiveC4/Champions#138]
#### Versions (Be specific, do not write "latest"):
* Champions: 1.16.5-2.0.1.14
* Forge: 36.2.39

#### Observed Behavior:
when I use the `/champions summon zombie 5` command it will summon a zombie with rank 5 and all the stats I have entered in my champions-ranks.toml file.
but when I use `/summon zombie ~ ~ ~ {ForgeCaps:{"champions:champion":{tier:5}}}` command it will summon a tier 5 zombie with all the stats I have entered in my champions-ranks.toml file EXCEPT the `presetAffixes` line
#### Expected Behavior:
I expected the entity to get all stats from the ranks file
#### Steps to Reproduce:
1. Add the following to your default config champions-ranks.toml file
`
[[ranks]]
  tier = 5
  numAffixes = 4
  defaultColor = 0xff0000
  chance = 0.0
  growthFactor = 500
  effects = ["minecraft:glowing"]
  presetAffixes = ["infested","magnetic"]
  `
2. Create a new world and use the following command
`
/summon zombie ~ ~ ~ {ForgeCaps:{"champions:champion":{tier:5}}}
`
3. note how affixes dont get appiled, but the glowing effect does
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by TheIllusiveC4** [comment]
Champions doesn't inject any special logic into the `/summon` command, so none of the normal checks would occur. The way that you've written the command only works with the tier because you're forcefully injecting that data into the entity's NBT tag.

The question I have now is what are you trying to do? The `/champions` command that you've mentioned is functionally identical to using the `/summon` command for the purposes of summoning a tiered champion and does apply special conditions such as preset affixes, but it seems you're specifically trying to use the `/summon` command for some reason.

**Comment by MasterSloth1** [comment]
so we have a mod that summons entities, we can change all the nbt tags of the entity. I want to spawn a specific mob and make it a champions mob, but i want 2 specific champions affixs and 2 randomly generated affixs
```json
{
              "entity": "blue_skies:summoner",
              "nbt": "{ForgeCaps:{\"champions:champion\":{tier:5,affixes:[{identifier:\"random\",data:{}},{identifier:\"random\",data{}},{identifier:\"magnetic\",data:{}},{identifier:\"infested\",data:{}}]}}}",
              "attributes": [
                {
                  "attribute": "minecraft:generic.max_health",
                  "level": 600
                },
                {
                  "attribute": "minecraft:generic.attack_damage",
                  "level": 40
                },
                {
                  "attribute": "minecraft:generic.armor",
                  "level": 40
                }
              ],
              "count": {
                "min": 2,
                "max": 5
              },
              "cooldown": {
                "min": 200,
                "max": 600
              },
              "offset": {
                "type": "minmaxCircle",
                "minHeight": -2000,
                "minRadius": 8,
                "maxRadius": 10
              }
            }
```

**Comment by TheIllusiveC4** [comment]
1.16.5-2.0.1.15 now supports NBT summoning. Read the full documentation [here](https://docs.illusivesoulworks.com/1.18.x/champions/nbt). Note that the documentation site is a WIP and only the 1.18.x version is available, but the information is still accurate for the 1.16.5 update.

**Comment by MasterSloth1** [comment]
OMG your amazing thank you so much
