### ISSUE TITLE
[1.18] Champions completely ignoring predefined affixes

### ISSUE THREAD

**Issue by Saereth** [TheIllusiveC4/Champions#139]
* Champions: champions-forge-1.18.2-2.1.6.0
* Forge: 40.1.80

#### Observed Behavior:
Define affixes for mobs, summon mobs and they are getting random affixes instead

#### Expected Behavior:
For the mobs to have the predefined affixes

#### Steps to Reproduce:
1. Setup affixes for the mobs, save in defaultconfigs and move to save/world/serverconfigs/champions-entites.toml
2. summon mobs in game
3. they will have random prefixes
...

Config file:
https://gist.github.com/Saereth/0bc90ccec058c082163e36ab338c898b

for example here the sickened skeleton from witherstormmod should have
```
[[entities]]
	entity = "witherstormmod:sickened_skeleton"
	minTier = 4
	maxTier = 4
	presetAffixes = ["Hasty", "Reflective", "Knocking", "Dampening"]
	affixList = []
	affixPermission = "BLACKLIST"

```

However in game...
![image](https://user-images.githubusercontent.com/9200909/197839175-27f16c37-12c9-459d-9faf-30d579ee5736.png)

This is the same for everymod I tested in here.
I previously had the extrachampions mod but disabled it for testing so its just champions currently 

Worth noting that the champion min/max tier DO work so the file is at least partially being respected.

**Comment by TheIllusiveC4** [comment]
Can you lowercase all of the affixes instead? So "hasty" instead of "Hasty". I should probably make that case-insensitive, but I just need to verify if that's the issue first.

**Comment by Saereth** [comment]
Sure thing I'll be able to test this in about an hour

**Comment by Saereth** [comment]
yep that was the issue, making them all lower case seems to have sorted it, thanks!
