### ISSUE TITLE
Suggestion: Desecrator Affix Enhancements

### ISSUE THREAD

**Issue by TeetoKaziim** [TheIllusiveC4/Champions#14]
As the desecrator affix currently stands, it's free damage at a fixed interval, as it seems to just spawn under the player's feet. Some things I think would make it more engaging to play against:

A visual indicator of some duration before the lingering potion of harming effect gets dropped. Maybe just like, a second, or so. Maybe a configurable number of ticks?

Configurable potion effect / magnitude / duration?

Some % amount of the desecrator patches that, rather than being dropped on a player, get dropped around the environment near the targetted player instead?

This mod, is RAD, by the way, can't stop reccomending it, it's a party every time :D.

**Comment by TheIllusiveC4** [comment]
Hmm, there are a few ways I could go about this. I'll take your ideas into consideration and see what I can do.
