### ISSUE TITLE
[1.18.2-2.1.6.0] Generating chunks lags the server / causes tps loss compared to v2.1.5.6

### ISSUE THREAD

**Issue by Thombias** [TheIllusiveC4/Champions#140]
#### Versions (Be specific, do not write "latest"):
* Champions: 2.1.6.0
* Forge: 40.1.84

#### Observed Behavior:
I noticed that chunk generation was really slow, so i checked the tps graph in the debug menu and it was all over the place. By using the mod Spark (a performance profiler) to check what was causing this it showed me that Champions eats about 2.29% of my server perfomance for not much reason. It was right at the top of the list, i had a few other mods installed as well but those were mostly 0.1% with very few at ~0.5% or so. I reverted back to version 2.1.5.6 and according to Spark the performance usage from that older version of the mod dropped down to a measly 0.12%

#### Expected Behavior:
The mod shouldn't cause the server side of the game to slow down to a crawl while generating chunks.
The issue is nowhere to be seen in v2.1.5.6

#### Steps to Reproduce:
1. Install mod version 2.1.6.0 and run the game, fly around a world in creative with the frame time and tps charts open or alternatively run the game with spark, activate the profiler, fly for a few minutes and then stop profiling.
2. Do the same but with mod version 2.1.5.6 and compare it with 2.1.6.0
3. The difference may vary but on average v2.1.6.0 will yield far worse server performance than v2.1.5.6

There is no crash log since it doesn't crash. I also left all configs at defautl values.

I can provide screenshots from my tps graphs as well as the spark performance profiles, specifically the percentual usage from champions alone. The tps graphs were captured right at the moment i was flying in creative and generating new chunks in a test world, since it is relatively stable when standing still.

Mod version 2.1.6.0
![tps graph 2 1 6 0](https://user-images.githubusercontent.com/46842890/197890885-af5231f9-3e10-4b42-89a2-315a6601e7a2.png)
![image](https://user-images.githubusercontent.com/46842890/197887680-d379718f-95f3-4a8c-ad14-1d4958d8c64e.png)

Mod version 2.1.5.6
![tps graph 2 1 5 6](https://user-images.githubusercontent.com/46842890/197890901-38d71eb0-2e2c-4560-ae97-3390e0918420.png)
![image](https://user-images.githubusercontent.com/46842890/197887778-2b3dd8f9-501f-4ce7-82cb-60f09eb3c936.png)

**Comment by TheIllusiveC4** [comment]
I do have a suspect on what's causing this, but are you able to attach the Spark profile report itself so I can peruse it myself and verify?

**Comment by Thombias** [comment]
I actually went ahead and did another test just to be doubly sure but this time i was only running champions + spark and nothing else. The issue is definitely reproducable from what i was able to gather. Here are the links to my spark profiles, i hope they work for you:
v2.1.6.0: https://spark.lucko.me/tDpSGcTjL6
v2.1.5.6: https://spark.lucko.me/SZZadh9lpx

At first glance they may look similar but from the short re-testing i did it was immediately visible just how much slower chunk generation was on v2.1.6.0. Entities were also quite laggy due to the unstable tps.

**Comment by TheIllusiveC4** [comment]
Okay, yeah, it was what I was suspecting. I'm honestly not sure how I'll address this because it's a tricky problem, but I'll see what I can do since it is a valid performance concern.

**Comment by TheIllusiveC4** [comment]
Can you try this test build and report back to me if the performance increases?

[champions-forge-1.18.2-2.1.6.1-snapshot.20221025.zip](https://github.com/TheIllusiveC4/Champions/files/9865677/champions-forge-1.18.2-2.1.6.1-snapshot.20221025.zip)

**Comment by Thombias** [comment]
I checked it out just now and can confirm it's fixed with the snapshot! Server usage from Champions dropped all the way down to just 0.05% compared to the 2.50% i had before with v2.1.6.0. Chunk generation was also able to keep up with me flying around in creative mode perfectly fine whereas with the other version i had to stop moving very often for it to catch up.

Here's the spark profile from my testing:
https://spark.lucko.me/MpxmrXZD8D

**Comment by TheIllusiveC4** [comment]
Great, these changes will be included in the next build which I will release once I've finalized one new feature I'm adding.

**Comment by BlackAures1** [comment]
I confirm that there are indeed problems with this 
https://spark.lucko.me/idHoSGw0Gl 
![image](https://user-images.githubusercontent.com/43911230/199192249-21592e84-370b-40b7-b876-ffd07ab23a76.png)

Version - champions-forge-1.18.2-2.1.6.0
