### ISSUE TITLE
Forge does not support multiple server configs for updating packs

### ISSUE THREAD

**Issue by Saereth** [TheIllusiveC4/Champions#141]
Running into an issue that effects pack updates pretty badly. Most changes get ignored now by the serverconfigupdater mod. I opened an issue with them regarding this but they said forge only supports a single config file so at present there is no way to automatically update packs with those changes. Would you consider consolidating the server configs or do you know of a work around? I know it's a big ask so if you have any other suggestions please let me know 

link to the specific issue:
https://github.com/Darkere/ServerConfigUpdater/issues/5

**Comment by TheIllusiveC4** [comment]
Consolidating the server configs into a single file is not really practical for many reasons. And I don't believe it's the ideal solution, ultimately I think Forge should be able to accommodate multiple config files.

For a work around, I might be able to just code support for ServerConfig Updater on my end. I'll have to look into it to see if it's feasible to do.

**Comment by Saereth** [comment]
Sounds fair, and yeah hopefully forge can support it in the future.. much appreciated for any solution you can come up with though. thanks for looking into it

**Comment by TheIllusiveC4** [comment]
This has been addressed by the developer of ServerConfigUpdater so I'll close this issue.
