### ISSUE TITLE
Concurrent Modification Crash

### ISSUE THREAD

**Issue by klugemonkey** [TheIllusiveC4/Champions#142]
* Champions:  2.1.6.0
* Forge: 40.1.80

#### Observed Behavior:

Server thread/ERROR and crash resulting from Concurrent Modification in ChampionHelper.java:61

#### Expected Behavior:

No Crash, iterating properly over the ticking entities without concurrent modification

#### Steps to Reproduce:

Unknown; while playing FTB Inferno, dropping down into a bastion near a ghast.

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

https://paste.atlauncher.com/view/55e7049b-ac4b-4c66-a567-82a4856dca13

**Comment by TheIllusiveC4** [comment]
This should be resolved in 1.18.2-2.1.6.1.
