### ISSUE TITLE
Champions, Beacon, Megatorch Server crash

### ISSUE THREAD

**Issue by MattB70** [TheIllusiveC4/Champions#144]
#### Versions (Be specific, do not write "latest"):
* Champions: 1.18.2-2.1.6.1
* Forge: 40.1.84

#### Observed Behavior:
A mod attempting to spawn as a champion whist in the radius of both a beacon and a Torchmaster Megatorch results in a server crash due to watchdog timeout.

#### Expected Behavior:
No mob should attempt to spawn whist in the range of a Megatorch, though this is usually not an issue, the beacon is definitely the culprit.

#### Steps to Reproduce:
1. Place beacon
2. Place Megatorch
3. Wait until a mob attempts to spawn with champion status
...

Crash Log: This is the crash that caused the immediate issue on our server, though possible to happen regardless of how it's recreated. [gist][(https://gist.github.com/](https://gist.github.com/MattB70/0ac8f690cd3e2b7b771a56ab6be1b44b)).

**Comment by TheIllusiveC4** [comment]
You state in the issue report that you have version 2.1.6.1, but your crash report shows you actually have 2.1.6.0 loaded. Please update the mod on your server and this crash should be fixed.
