### ISSUE TITLE
Champions' 'Boss Bar' renders multiple times (causing compatibility issues)

### ISSUE THREAD

**Issue by Exopandora** [TheIllusiveC4/Champions#146]
The 'Boss Bar' of champions renders multiple times per frame causing visual issues as seen [here](https://github.com/Exopandora/ShoulderSurfing/issues/99). This is due to wrong usage of `RenderGameOverlayEvent` in [`ClientEventHandler`](https://github.com/TheIllusiveC4/Champions/blob/1.18.x/src/main/java/top/theillusivec4/champions/client/ClientEventHandler.java#L22), which is likely by mistake. The event itself uses `RenderGameOverlayEvent.BossInfo.Pre`, but `Pre` is not actually a subclass of `RenderGameOverlayEvent.BossInfo`, but instead a subclass of `RenderGameOverlayEvent` itslef (to be honest, i don't even know why the compiler doesn't throw an error here). Therefore the event gets triggered by every `RenderGameOverlayEvent` in the `Pre`-Phase, resulting in multiple draw calls for your boss bar. For now, i see two possible solutions to this problem:
1)
Change `RenderGameOverlayEvent.BossInfo.Pre` to `RenderGameOverlayEvent.PreLayer` and check for`ForgeIngameGui.BOSS_HEALTH_ELEMENT == event.getOverlay()`, else just return. To then prevent other boss bars from redering, you can create a new event, listening for `RenderGameOverlayEvent.BossInfo`, which is called for each boss bar _individually_, and cancel that event.
2)
You render your custom boss bar using the `RenderGameOverlayEvent.BossInfo` event, and only render it when the player is looking at the champions mob. Though, in order for this to work, you would need to register your boss bar somehow, and i don't know how that exactly works. But it would have the advantage, that other boss bars could be visible at the same time.

**Comment by TheIllusiveC4** [comment]
Huh, interesting. I guess no one ever realized because this is normally never noticeable. This seems like a simple enough fix, will probably have something out later today.
