### ISSUE TITLE
[1.16.5]What is the range of weight? I don't know much about Java

### ISSUE THREAD

**Issue by QWQMUSHU** [TheIllusiveC4/Champions#149]
Here's a code
#Format: [tier];[modid:name];[amount];[enchant(true/false)];[weight]

My doubt is the range of weight, i.e. I want beef to drop probability of 30%, but when I change weight to 0.3, he shows that this is not a valid value. How do I fill in to change the drop probability to 30%?

**Comment by TheIllusiveC4** [comment]
Weight is a property that adds itself to every other entry in that same tier. It can only ever be whole numbers, not decimals. If you had three entries for tier 1 at weight 1, the total weight would be 3 (3 * 1) and each entry with weight 1 would have a 33% chance of dropping.

You could only achieve a probability of 30% by adding other entries also to balance it. You _might_ be able to fake it by making your entry weight 3 and another entry for `minecraft:air` as an item with weight 7, but I've never tested this case.

The proper way to do this would be a loot table that overrides the default one:
https://github.com/TheIllusiveC4/Champions/blob/1.16.x/src/main/resources/data/champions/loot_tables/champion_loot.json
