### ISSUE TITLE
Big Problem with Champions and Aether Legacy Sun spirit

### ISSUE THREAD

**Issue by SirAron111** [TheIllusiveC4/Champions#16]
Ok here is the thing if the sun spirit ever gets any champion trait especially things like infested since he has a strange ai that makes him attack infinitely but instead uses special attacks he basically summons a million silverfish or potion effects etc. You should look into this or at least make the sun spirit blacklisted mob by default XD. Just wanted to let you know.

**Comment by TheIllusiveC4** [comment]
I've just blacklisted it by default. Since it's a modded entity, there's not much I can do on my end if their AI is set up to attack that way.
