### ISSUE TITLE
[Feature Request] Custom NPC's Support

### ISSUE THREAD

**Issue by duhadventure** [TheIllusiveC4/Champions#2]
Would it be possible to add a tab to the CustomNPC's NPC creation tool when this is installed so that the NPCS can use these abilities?

**Comment by TheIllusiveC4** [comment]
It might be possible, but I don't think I'm going to try and implement this at the moment. CustomNPCs system is quite complex and I just don't know enough about it to even know if this is possible or not, let alone all of the overhead involved. I'm also not sure that trying to inject additional AI into their NPCs won't cause issues in itself.
