### ISSUE TITLE
Champion’s abilities can crash the game when mob killers attack them or they try to attack them back

### ISSUE THREAD

**Issue by SirAron111** [TheIllusiveC4/Champions#22]
#### Versions (Be specific, do not write "latest"):
* Champions: champions-1.12.2-1.0.8.jar
* Forge:1.12.2 - 14.23.5.2825

#### Observed Behavior:
It seems the knockback function of the champions doesn’t go well with mob grinders if a champion spawns on cursed earth or with another method or simply walls in range of the industrial forgoing mob crusher or the draconic evolution mob grinder. Certain abilities give it a hard time or crash.
Shielding or damage reducing abilities can protect the mob even from non player sources like these grinders.
If they try to attack the block back with abilitys like knockback it crashes also. 

#### Expected Behavior:
mob gets normaly gridned not crashing.
The function for preventing champion item drops from grinders works great thought thumbs up for that one.

#### Steps to Reproduce:
1.Spawn champions in front of active grinders. Than wait for all the different crashes!
2.thats all

Crash Log: Please use a paste site like [gist] https://pastebin.com/pAeqmZ1p

**Comment by TheIllusiveC4** [comment]
Can you see if it still crashes without Rough Mobs 2? It seems to me that may be the main issue, because the Knockback affix is being triggered by the defending abilities that the mod gives to Blazes, which is outside my control. I could implement a check there, but I think it makes more sense for them to just not try to attack fake players at all. 

> Certain abilities give it a hard time or crash.

Are there other ones that crash besides Knockback? You'll have to be as specific as possible so I can look into each possible source of error.

And are you asking to allow shielding/damage reducing abilities to be bypassed by grinders? Personally I think the current behavior sounds fair, but I can add that as a config option.

**Comment by SirAron111** [comment]
Thx for the fast response. The crash log was sent to me by a player on a server of my pack I to thought it must have been something regarding the strange combination of the affixes and the blaze modifier. That’s why I also reported the issue to the rough mobs author. At the same time https://minecraft.curseforge.com/projects/rough-mobs-2/issues/40

As for other affixes that crash the game there was the one with the silverfish that when a mob tried to attack the grinder making it spawn silverfish on no end would be nice if the function to spawn silverfish had a cool down so even if its set to spawn silverfish on taking or doing dmg it can’t do more than one (x amount at once) until the cool down is back like there is for the arctic one.

As for now there weren’t any problems with shielding in itself that is if it is alone. (but if a mob with more abilities spawns and has shielding it gets aggroed by the mob killers and targets them and since they take a bit of time to work the mob will then have more time to trigger new possible errors as it doesn’t get killed before it can target anything) by simply turning of the special drops for mob grinders they are nothing more than normal mobs for them so it shouldn’t be a problem if they ignore grinders/crushers etc.

**Comment by SirAron111** [comment]
Damn there really should be a way to prevent mobs from targeting or getting revenge target on machines. Last time the wizards from electroblobs caused a crash with crushers now this XD. Sry about that I find all the bugs.

**Comment by SirAron111** [comment]
https://github.com/brandon3055/Draconic-Evolution/issues/1290#issuecomment-481299531

**Comment by TheIllusiveC4** [comment]
The crash log there is still triggered by the Rough Mobs' defending behavior, so my comment is still the same as above. This needs to be fixed by the Rough Mobs developer so that they do not try to knockback instances of fake players.

**Comment by TheIllusiveC4** [comment]
Alternatively, I can implement a fix on my end if you can produce a crash log without Rough Mobs' defending behavior involved.

**Comment by SirAron111** [comment]
https://minecraft.curseforge.com/projects/rough-mobs-2/issues/40 i already noted it there as well Thought he didn’t respond jet. So all I can do for now is playing the waiting game XD until than I disabled the feature from blazes in my pack till it’s fixed.
