### ISSUE TITLE
Enhancement: Improving the specific mob function for always champion.

### ISSUE THREAD

**Issue by SirAron111** [TheIllusiveC4/Champions#23]
Is it possible to have the “is always champion function to be a bit more configurable?”

I have set it up so that for example boss mobs and certain others are always champions. This in itself works great but I have run into some limitations in my configurability options.

I set to balance the champions out a bit certain affixes to only appear on mobs with 2 or 3 starts meaning a 1 star can’t have for example scrapper or plague but only arctic and hast etc. this also works great.

And here is the problem I wanted to set certain bosses to always have a certain function for example the ice queen from the twilight forest should always have the slow effect and the crusshrom from the Erebus should always have infested. The snow queen works fine as the slow one is set to appear on 1 star mob so it always is on the queen. But for the crushshroom since I set the infested to only appear on 2 star mobs it doesn’t always appear on him only if he actually gets to be a 2 star mob.

Also if for example a boss that is always set to be champion gets randomly 4 stars they are unintentionally super op.

Is it possible for one to always have the mobs that have specific affixes set to them in the config to always have them even if they don’t fulfill the star requirement? And second is it possible to lock the star level of a mob that is set to always be a certain level?

So that I can say for example snow queen always 2 star with always slow and whatever as second skill. And Crushshroom always 3 star with infested to always be there or to always make him 1 star and never more and still have the infested one even if its set to only appear on 2 star mobs to balance out the general mobs.

This would greatly improve configurability for bosses and if wanted other mobs.

**Comment by TheIllusiveC4** [comment]
I've implemented both your suggestions. Specific affixes will now avoid validity checks and tier checks so they will always be present as intended. And the always champions mob list config option now has an additional optional parameter to specify tier (i.e. "minecraft:spider;2 will always make spiders tier 2").
