### ISSUE TITLE
Champions Crash occasionally with Special Mobs for no discernible reason

### ISSUE THREAD

**Issue by Jackiecrazy** [TheIllusiveC4/Champions#24]
#### Versions (Be specific, do not write "latest"):
* Champions: 1.0.8
* Forge: 2823

#### Observed Behavior:
No apparent cause. The crash log seems like Special Mobs was trying to replace a champion? I know I should probably take this to FatherToast...
#### Expected Behavior:
Not crashing
#### Steps to Reproduce:
1. Install Special Mobs and Champions
2. Enter a world
3. Wait a bit, cranking up mob spawns would probably help

Crash Log: https://pastebin.com/wRZbEvmi

**Comment by TheIllusiveC4** [comment]
It looks like the capability is null at that time for some reason, which really shouldn't happen. I'm not sure what's causing that, perhaps it's a timing thing with Special Mob's replacement method. I can address the crashing at least, but there may still be further problems down the line that have yet to reveal themselves.
