### ISSUE TITLE
Loot Tables

### ISSUE THREAD

**Issue by DrCo** [TheIllusiveC4/Champions#25]
#### Steps to Reproduce:
1. I read the config file, and it is set to loot_table, because there is it was too difficult to decipher the values to set if CONFIG, format is tier;modid:name;metadata;stacksize;enchant(true/false);weight
Would this mean 4 ; creeper ; minecraft:emerald ; 1 ; false ; 1

Could this be described further?

2. I tried following the Loot Table Primer by changing the loot table  .json, but I'd need to use the source and recreate a .jar file

3. I could use LootTweaker, but it would replace existing tables and entity values aren't clear

My desired loot table .json is
{
  "pools": [
    {
      "name": "tier#1",
      "rolls": 1,
      "entries": [
        {
          "type": "item",
          "name": "minecraft:emerald",
          "weight": 1,
          "conditions": [
            {
              "condition": "entity_properties",
              "entity": "this",
              "properties": {
                "champions:is_champion": {
                  "min_tier": 1
                }
              }
            },
            {
              "condition": "killed_by_player"
            }
          ]
        },

          {
            "type": "item",
            "name": "minecraft:book",
            "weight": 0.7,
            "conditions": [
              {
                "condition": "entity_properties",
                "entity": "this",
                "properties": {
                  "champions:is_champion": {
                    "min_tier": 1
                  }
                }
              },
              {
                "condition": "killed_by_player"
              }
            ],
            "functions": [
              {
                "function": "enchant_randomly"
              }
            ]
          }
      ],
    },
    {
      "name": "tier#2",
      "rolls": 2,
      "entries": [
        {
          "type": "item",
          "name": "minecraft:diamond",
          "weight": 0.6,
          "conditions": [
            {
              "condition": "entity_properties",
              "entity": "this",
              "properties": {
                "champions:is_champion": {
                  "min_tier": 2
                }
              }
            },
            {
              "condition": "killed_by_player"
            }
          ]
        },

          {
            "type": "item",
            "name": "minecraft:wither_skeleton_skull",
            "weight": 0.3,
            "conditions": [
              {
                "condition": "entity_properties",
                "entity": "this",
                "properties": {
                  "champions:is_champion": {
                    "min_tier": 2
                  }
                }
              },
              {
                "condition": "killed_by_player"
              }
            ]
          }
      ],
    },
    {
      "name": "tier#3",
      "rolls": 1,
      "entries": [
        {
          "type": "item",
          "name": "minecraft:diamond",
          "weight": 2,
          "conditions": [
            {
              "condition": "entity_properties",
              "entity": "this",
              "properties": {
                "champions:is_champion": {
                  "min_tier": 3
                }
              }
            },
            {
              "condition": "killed_by_player"
            }
          ]
        },

          {
            "type": "item",
            "name": "minecraft:dragon_egg",
            "weight": 0.3,
            "conditions": [
              {
                "condition": "entity_properties",
                "entity": "this",
                "properties": {
                  "champions:is_champion": {
                    "min_tier": 3
                  }
                }
              },
              {
                "condition": "killed_by_player"
              }
            ]
          }
      ],
    },
    {
      "name": "tier#4",
      "rolls": 4,
      "entries": [
        {
          "type": "item",
          "name": "minecraft:elytra",
          "weight": 0.2,
          "conditions": [
            {
              "condition": "entity_properties",
              "entity": "this",
              "properties": {
                "champions:is_champion": {
                  "min_tier": 4
                }
              }
            },
            {
              "condition": "killed_by_player"
            }
          ]
        },

          {
            "type": "item",
            "name": "minecraft:enchanted_golden_apple",
            "weight": 0.3,
            "conditions": [
              {
                "condition": "entity_properties",
                "entity": "this",
                "properties": {
                  "champions:is_champion": {
                    "min_tier": 4
                  }
                }
              },
              {
                "condition": "killed_by_player"
              }
            ]
          }
      ],
    }
  ]
}

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by TheIllusiveC4** [comment]
You'll have to first decide whether you want to use CraftTweaker + LootTweaker or use the vanilla loot table system. Also note that while the vanilla loot table system does only override/replace existing loot tables, LootTweaker is not limited in this same way and can make additive edits.

**Comment by TheIllusiveC4** [comment]
I'll be closing this since there has been no follow-up and it's currently unclear whether the OP wants to use CraftTweaker + LootTweaker or the vanilla loot table overrides. If there are still questions or concerns, reply back or join the Discord channel, the latter of which might be more appropriate for general questions like this.

**Comment by Erycus** [comment]
Hello.  I really enjoy your mod and it's great for adding balance to modded servers.  I don't want to open a new 'issue' as there's nothing wrong, but I'm not sure how otherwise to ask about the config options and loot tables.

Could you tell if the table in champions.config supports NBT data or not?  
If not I guess then I need to read through Loot Tweaker's docs.

**Comment by TheIllusiveC4** [comment]
It supports whatever loot tables normally support, I don't know if that includes NBT data. If you can do it for a vanilla entity loot table, you can do it for the Champions loot table.

**Comment by Erycus** [comment]
Ok, thank you!  What I personally ended up doing was editing the champion_loot.json file in champions-1.12.2-1.0.11.8.jar\assets\champions\loot_tables\ and then deleting the META-INF folder in the jar.

I just wanted to change the drops server-side of a standard modpack and ended up doing it that way.

For others who might end up coming across here:
How I chose to modify the json is here: https://nxtcld.tech/s/H7HGsF2SJPqRE3z
Compare with the original here: https://github.com/TheIllusiveC4/Champions/blob/1.16.x/src/main/resources/data/champions/loot_tables/champion_loot.json

Important documentation: https://github.com/TheIllusiveC4/Champions/wiki/(1.12)-Loot-Table-Primer
You _must_ set a tier/max_tier/min_tier if you **don't** want a loot table entry to drop from ALL champions.
"Leaving out all of these fields is a valid configuration and will result in the loot being dropped by all champions."
