### ISSUE TITLE
Cross Mod Crash with MultiMob

### ISSUE THREAD

**Issue by Mattabase** [TheIllusiveC4/Champions#26]
* Champions: champions-1.12.2-1.0.9 
* Forge: 14.23.5.2838 
* MultiMob: multimob-1.0.5

#### Steps to Reproduce:
1.Be in a world
2.Let a Champion spawn
...

Crash Log: https://gist.github.com/Mattabase/c55c4f3d3bf5560bfb6436372bdbb50c

Mod Links
https://minecraft.curseforge.com/projects/champions
https://minecraft.curseforge.com/projects/multi-mob-core

[https://github.com/Daveyx0/MultiMob/issues/32](url)

**Comment by TheIllusiveC4** [comment]
I couldn't reproduce this, my testing environment worked fine with MultiMob no matter how many champions spawned. However, I've made some changes that should at least prevent this issue from happening in the future.
