### ISSUE TITLE
Enhancement: Adjustable damage for the molten class.

### ISSUE THREAD

**Issue by SirAron111** [TheIllusiveC4/Champions#27]
I ran into a little problem the molten damage could it be that it uses the damage class for fire or lava vanilla mc uses? Would it be possible in the next update or so to add a config for how much damage it does when touching/gettingattacked by a molten enemy? I pumped up the damage that touching fire and lava does via the dmg classes but this seems to also affect molten mobs (well I made this effect a tier 3 and up only effect like plague and so) but it still comes around rather deadly when a molten mob hits you for 50+ dmg.

BTW I like what you did with the infested ones the silverfish are way easier to handle now. Especially giving the mob a cap on how much it can have at a time and a timer in between spawns. Maybe scaling against max hp isn’t the best since mods like scaling health can easily give mobs over 1k hp maybe just have that scale to the amount of stars the champion has.

**Comment by TheIllusiveC4** [comment]
How exactly are you increasing the damage? Molten doesn't use any particular damage class, it takes the original damage source and 1) gives it the magic property and 2) sets the target on fire.

**Comment by SirAron111** [comment]
I am using a mod called damage controll. This one looks for any damage that gets applied in game and sees to the dmg class connected. To give thes classes a modifier like for example:
inFire
drawn
generic
mob
basically like this 
https://pastebin.com/nwF28jQT
but now that you say you use the magic property and original dmg I think I know why it must be due to the class being the normal ones as they are multiplied to increase mob dmg and the like

**Comment by TheIllusiveC4** [comment]
It doesn't attack twice, Molten doesn't add any additional attacks at all. It just changes the original damage source to have the magic property right before it hits. If I'm understanding that other mod correctly, the damage modifier should be exactly the same with/without Molten. Are you sure these numbers are actually being inflated? It could be hitting for more damage simply because of the magic property's armor-piercing nature.

**Comment by SirAron111** [comment]
could be
