### ISSUE TITLE
Suggestion: Config to disable champions from spawners

### ISSUE THREAD

**Issue by Shadows-of-Fire** [TheIllusiveC4/Champions#3]
I like the concept here, but certain champion affixes are creating significant issues in mob farms, plus the enchanted book spam is less than ideal in a farm.  

Being able to block champion spawns from spawners would be greatly appreciated.

**Comment by TheIllusiveC4** [comment]
Are you talking about just vanilla spawners or maybe some other methods as well?

**Comment by majijn** [comment]
I haven't received any champions from spawners in my testing worlds, weird.

**Comment by Shadows-of-Fire** [comment]
I was mainly referring to vanilla spawners.  Changing the event from join world to SpecialSpawn (and checking if a spawner made the entity) was successfully able to block them from showing up in spawners
