### ISSUE TITLE
[Suggestion] A way to set the spawn rate

### ISSUE THREAD

**Issue by Kehaan** [TheIllusiveC4/Champions#37]
Hello

I am usually using InfernalMobs, but dicovered this mod. And so far i like it a lot!

However, i can't find a place where i can chance how often a mob should spawn as a champion? Is that not something you can chance? Like in InfernalMobs, you can se how often a mob should spawn as a infernal x tier.

Thanks.

- Kehaan

**Comment by TheIllusiveC4** [comment]
This is possible already, it's located in `config/champions` in `ranks.json'. For more info, see here: https://github.com/TheIllusiveC4/Champions/wiki/Ranks-JSON
