### ISSUE TITLE
Feature Request: Item to apply modifiers

### ISSUE THREAD

**Issue by duhadventure** [TheIllusiveC4/Champions#4]
Feature Request:  Add an item that opens a gui that you can select affixes to apply to a mob, then spawns mob from list of available entities.

**Comment by TheIllusiveC4** [comment]
I'm not against this per say, but I'd like to ask what's your exact use case for such a feature? Since this is essentially granting people a spawn egg, is there some purpose in doing so?

**Comment by duhadventure** [comment]
> I'm not against this per say, but I'd like to ask what's your exact use case for such a feature? Since this is essentially granting people a spawn egg, is there some purpose in doing so?

Creating bosses that I can copy with admin tools to spawn whenever I want
