### ISSUE TITLE
Random Range in Always Spawn as Champion Config

### ISSUE THREAD

**Issue by axin0452** [TheIllusiveC4/Champions#40]
```
    # List of mobs that will always spawn as champions, can optionally include specific tier (i.e. 'minecraft:spider;2')
    S:"Champion Mobs List" <
        minecraft:zombie;1
     >
```

This section can make zombies generate 1 star, so how to make them random in 1 ~ 2?
minecraft:zombie;1~2
I don't speak English well, can you understand what I mean?

**Comment by TheIllusiveC4** [comment]
That's not currently a feature, but I can look into adding it into the next update.

**Comment by axin0452** [comment]
thank you very much
@TheIllusiveC4
