### ISSUE TITLE
Plague effect infects armor stands

### ISSUE THREAD

**Issue by EMifnick** [TheIllusiveC4/Champions#45]
#### Versions (Be specific, do not write "latest"):
* Champions: champions-1.12.2-1.0.11.3.jar
* Forge: ForgeMultipart-1.12.2-2.6.2.83-universal.jar
NOTE: Observed in MC Eternal Lite, could not get mod to run alone to reproduce as instructed. Apologies.
#### Observed Behavior:
Plague mobs, when near two vanilla armor stands, infect them. Armor stands show no indication of being infected, but nevertheless will infect nearby players. Effect is perpetual because armor stands don't die, and keep infecting each other. This creates a mysterious no-go zone even after the original champion mob is dead, and players can go for a long time without realizing the armor stand is the culprit (as I did).
#### Expected Behavior:
Plague should not infect armor stands- it doesn't even make sense, and only happens because armor stands are technically mobs. (They die to the /killall command, which can even fool players into thinking they killed a hidden actual mob causing the problem, which is so weird.)
#### Steps to Reproduce:
1. Put two armor stands in close proximity to each other.
2. Spawn a plagued mob of any sort, or (I imagine) just walk near them while yourself plagued.
3. Kill the plagued mob.
4. Suffer.

**Comment by V-Boy** [comment]
Wow I can't believe that this was the issue the whole time lol. I would've never suspected the constant plague poisoning to be our stands
