### ISSUE TITLE
Mob spawner

### ISSUE THREAD

**Issue by Xitryne** [TheIllusiveC4/Champions#46]
#### Versions (Be specific, do not write "latest"):
* Champions: 1.0.11.8
* Forge: 1.12.2 (14.23.5.2854)

#### Observed Behavior:
I currently have the Roguelike Dungeon mod, it shows structures with mobs spawners inside but champions mobs appear thanks to these spawners, except I deactivated the option to show champions mobs via the mobs spawners.

#### Expected Behavior:
I wish monster champions didn't appear in these mobs spawners.

#### Steps to Reproduce:
1.I have already disabled/enabled the "Champions from Spawners" option. 
2.I checked with mobs spawners in vanilla structures and no champion mobs show up.

Crash Log: Please use a paste site like [gist](https://gist.github.com/).

**Comment by TheIllusiveC4** [comment]
If the option works for vanilla mob spawners but not Roguelike Dungeons spawners, then this will have to be fixed on Roguelike Dungeons's side. Likely, the way they're spawning mobs is bypassing the Forge spawn event that Champions uses to check for spawns from spawners.
