### ISSUE TITLE
Champions config folder is not being created

### ISSUE THREAD

**Issue by Jaeiya** [TheIllusiveC4/Champions#52]
#### Versions (Be specific, do not write "latest"):
* Champions: FORGE-1.15.2-2.0-beta3
* Forge: 31.2.30

#### Observed Behavior:
No `ranks.json` file is generated, nor was a `champions` folder created in the config folder.

#### Extra Info:
I tested this with minimal mods (JEI and Controlling) to make sure it wasn't somehow a mod conflict.

#### Expected Behavior:
To see a `ranks.json` file within a `champions` folder in the config directory.

#### Steps to Reproduce:
1. Launch game with mod installed.

**Comment by TheIllusiveC4** [comment]
Champions has server-side configs in 1.14+, which is created by Forge in the world save's `serverconfig` folder. Please look there to find the relevant files.

**Comment by Jaeiya** [comment]
Is there documentation that says this somewhere that I overlooked?

**Comment by TheIllusiveC4** [comment]
Yes, it's part of the README file included in the mod jar and on this GitHub repo.
https://github.com/TheIllusiveC4/Champions/blob/1.15.x/docs/README.md

But I did realize that I forgot to update the wiki and the CurseForge project page accordingly, so sorry about that.

**Comment by Jaeiya** [comment]
> But I did realize that I forgot to update the wiki and the CurseForge project page accordingly, so sorry about that.

No problem; I'm just happy that you're active enough to be able to address small issues like this ❤️ 

Thanks!
