### ISSUE TITLE
How to change monster rewards without using LootTweaker

### ISSUE THREAD

**Issue by axin0452** [TheIllusiveC4/Champions#58]
https://github.com/TheIllusiveC4/Champions/wiki/(1.12)-Loot-Table-Primer
Sorry, I really didn't understand how to change the reward

**Comment by TheIllusiveC4** [comment]
If you're new to loot tables, you could consider using the config option for loot instead.

**Comment by axin0452** [comment]
@TheIllusiveC4  
What is the calculation formula of monster life.In any case, I can’t calculate a value that matches the actual HP. This prevents me from accurately setting the strength of the monster.

**Comment by TheIllusiveC4** [comment]
The calculation is based off two values. One is the health growth value in champions.cfg. The other one is the growth factor in ranks.json. Then the formula is just base health * (1 + (health growth percentage * growth factor)).
