### ISSUE TITLE
Villagers Wont become Champions

### ISSUE THREAD

**Issue by XxNeapTidexX** [TheIllusiveC4/Champions#61]
Hello! this is more of a suggestion than a bug or something, but im not sure if villagers are by default not allowed to become champions or if im putting them in the whitelist incorrectly. But i think it would be hilarious if we could make villagers OP. the syntax i used was minecraft:villager;1 by the way. Thank you for your time!

**Comment by TheIllusiveC4** [comment]
Villagers are not considered valid champion mobs, since they are considered passive. I may change my mind at some point, but currently I do not have any plans to change that behavior.
