### ISSUE TITLE
No Drops?

### ISSUE THREAD

**Issue by OnlyCrimson** [TheIllusiveC4/Champions#65]
#### Versions (Be specific, do not write "latest"):
* Champions: 1.16.3-2.0.0.1
* Forge: 1.16.3 34.1.42

#### Steps to Reproduce:
1. Idk, it just started happening.
2.
3.
...

Crash Log: It never crashed.

**Comment by OnlyCrimson** [comment]
I'm pretty sure I found the issue; the champions don't drop anything when I kill them in one hit.

**Comment by TheIllusiveC4** [comment]
I cannot reproduce this issue. Killing Champions in a single hit drops as expected. Have you replicated this issue with only Champions installed? Otherwise, it could be a mod conflict.
