### ISSUE TITLE
Server error when logging in as operator

### ISSUE THREAD

**Issue by linx80** [TheIllusiveC4/Champions#74]
#### Versions (Be specific, do not write "latest"):
* Champions: 1.16.5-2.0.1.3
* Forge: 1.16.5-36.0.42

#### Observed Behavior:
When an server operator logs into server, this error message appears in console.
[08:42:11] [Netty Epoll Server IO #3/ERROR] [minecraft/ArgumentTypes]: Could not serialize top.theillusivec4.champions.server.command.AffixArgument@3bc07b6d (class top.theillusivec4.champions.server.command.AffixArgument) - will not be sent to client!
#### Expected Behavior:
No error error message.
#### Steps to Reproduce:
1. Log in as server operator
2.
3.
...

Crash Log: Please use a paste site like [gist](https://gist.github.com/).
Server doesn't crash though...

**Comment by TheIllusiveC4** [comment]
This isn't anything to worry about, so don't mind it.

But I'll leave this open because I might as well try and figure out how to stop this error log in the first place.
