### ISSUE TITLE
Setting chance = 0 in ranks config causes a crash

### ISSUE THREAD

**Issue by Lystraeus** [TheIllusiveC4/Champions#75]
Champions: 2.0.1.4
Forge: 36.0.45

Seems to be interpreting 0 as an integer, rather than a double. As a stop-gap the wiki could say any double from 0.0 to 1.0

**Comment by TheIllusiveC4** [comment]
The wiki has been updated to reflect that the number must be a decimal number between 0.0 to 1.0.
