### ISSUE TITLE
crash on world join

### ISSUE THREAD

**Issue by Wedge1453** [TheIllusiveC4/Champions#78]
[crash-2021-03-17_21.54.57-server.txt](https://github.com/TheIllusiveC4/Champions/files/6159986/crash-2021-03-17_21.54.57-server.txt)

**Comment by TheIllusiveC4** [comment]
Alright so this is a simple fix, but this isn't something that should be happening in the first place. This seems to indicate that your ranks configuration is completely empty or missing, which is not expected behavior.
