### ISSUE TITLE
Crash related with Lyca Mobs

### ISSUE THREAD

**Issue by Xaikii** [TheIllusiveC4/Champions#8]
#### Versions (Be specific, do not write "latest"):
* Champions: 1.12.2-1.0.2
* Forge: forge-14.23.5.2796

#### Observed Behavior:
A Random occuring Crash

#### Expected Behavior:
Running casually

#### Steps to Reproduce:
1. I do not even know, I didn't do anything

####Note:
I removed the Notice Parts, since I assume this is a Compat Issue with another Mod and I therefore didnt test without everything else. Also like I said, I do not know what caused it exactly, I have been in another tab while it crashed... in other words... I did nothing.

Crash Log: https://pastebin.com/J5Lkw9XX

**Comment by TheIllusiveC4** [comment]
I have some suspicions. What do you have for the config for "Silverfish on Death" in the Infested affix category?

Well regardless, definitely a bug since I should be testing for a positive integer either way. I'll have a new update out soon for that.

**Comment by Xaikii** [comment]
I have set both to 0, I should have probably disabled it instead of set it to 0 when I think about it right now.
