### ISSUE TITLE
Champions health bars aren't affected by mods that move boss bars.

### ISSUE THREAD

**Issue by Foozey** [TheIllusiveC4/Champions#82]
Example Mods:
https://www.curseforge.com/minecraft/mc-mods/advanced-compass
https://www.curseforge.com/minecraft/mc-mods/hud-compass

**Comment by TheIllusiveC4** [comment]
This should be addressed in the latest 2.0.1.8 version as a part of https://github.com/TheIllusiveC4/Champions/issues/96; however, I believe Advanced Compass needs an update for this as well on their end to check for any canceled render events.
