### ISSUE TITLE
Crash upon starting the world out of no where

### ISSUE THREAD

**Issue by BugmanBugman** [TheIllusiveC4/Champions#83]
#### Versions (Be specific, do not write "latest"):
* Champions: 2.0.1.7

* Forge: 36.1.23

#### Observed Behavior:

Right when creating my hardcore world and joining it, the game crashed and kicked me out. No idea why, so right now i'm unable to reproduce it. Just wanted to report the crash log to you

Crash Log: Please use a paste site like [gist](https://gist.github.com/).
[crash-2021-05-21_10.37.19-server.txt](https://github.com/TheIllusiveC4/Champions/files/6523629/crash-2021-05-21_10.37.19-server.txt)

**Comment by TheIllusiveC4** [comment]
I am unable to reproduce this, so I'm not sure what the cause could be. I can add some safeguards but its helpfulness is limited without knowledge of the source of the issue.

Did you modify the configs in any way?

**Comment by BugmanBugman** [comment]
No not at all. It was all default configs
