### ISSUE TITLE
Random crash on world load

### ISSUE THREAD

**Issue by Jackiecrazy** [TheIllusiveC4/Champions#84]
#### Versions (Be specific, do not write "latest"):
* Champions: 2.0.1.7
* Forge: 36.1.16

#### Observed Behavior: 
When creating a new world with a custom datapack, it may randomly crash. The game does not exit, but the world will be stuck on "generating world". Killing the game and reopening it will allow loading of the world without issue.
#### Expected Behavior:
The game should not crash.
#### Steps to Reproduce:
1. create a new world. In the datapack section, use the json attached.
2. it may or may not crash. If it does not, it will never crash for that session, even if step 1 is repeated.
3.
...

Crash Log: [crash report and datapack json](https://gist.github.com/Jackiecrazy/a31b4c3ef485a15b551e10eaf4df7ded).

**Comment by lynnpye** [comment]
For what it's worth, I've also been experiencing this with a modpack I've been playing with. I had been using the latest version of Champions (2.0.1.7). Reverting back to 2.0.1.5 allowed me to do a re-create on the same original "stuck" world but it actually let me join the game. I'm trying to work out what all isn't playing nicely together as well, but thought this info might help.

EDIT: FWIW, removing Bloxys Structures seemed to allow me to use latest Champions.
