### ISSUE TITLE
crashing after changing champions-ranks.toml

### ISSUE THREAD

**Issue by Winesage** [TheIllusiveC4/Champions#86]
Versions 
* Champions: 2.0.1.7
* Forge: 36.1.31

Observed Behavior:
I have a custom modpack and the game crashes when I make a new world if not it crashes after I walk around for a bit. I have changed the rank config to make all new spawns rank 1. Might be another mod's mob being a champion thus causing the crash if it could happen I don't know much about these stuff. The game seems to be working fine without the champions mod.

Steps to Reproduce:
1. new world default config for champions mod with my modpack 
2. change rank for all new spawns to rank 1 
3. prob gonna crash soon I had times where I crashed after 2 minutes or instantly on world creation.
...

Crash Log: https://gist.github.com/Winesage/6e75e5f60ed0f1ed500c08c22737f927

**Comment by TheIllusiveC4** [comment]
Can I see your `champions-ranks.toml` file?

**Comment by Winesage** [comment]
so I tried both with tier 0 and without tier 0
https://gist.github.com/Winesage/2e437f92716a48d0b8f28d68885e50bc

**Comment by TheIllusiveC4** [comment]
So if you have it with tier 0, and then set tier 1 to `chance = 1.0`, this crash still occurs right?

**Comment by Winesage** [comment]
yes

**Comment by TheIllusiveC4** [comment]
Okay, one more thing. Does this crash still occur if you do the same thing with _only_ Champions installed?

**Comment by Winesage** [comment]
I can try it right now if you give me a few minutes

**Comment by Winesage** [comment]
Didn't crash yet I tried with rank 0 and without rank 0 again.

**Comment by TheIllusiveC4** [comment]
Then unfortunately it sounds like it could be a mod conflict, and I can't tell which one just from the crash log.

**Comment by Winesage** [comment]
I will see if I can test it 1 by 1 with each mod that has a custom mob in it.
