### ISSUE TITLE
changing attributes config breaks world creation

### ISSUE THREAD

**Issue by NixityNull** [TheIllusiveC4/Champions#90]
for me, setting the plagued attribute to whitelist and adding mob ids (ex: [minecraft:zombie, minecraft:husk]) causes the game to lag intensely and refuse to load worlds. 

I am using 1.16.5 and there are no mods that are causing incompatibility issues

**Comment by NixityNull** [comment]
scratch that, changing anything in the defaultconfig file makes it refuse to run

**Comment by TheIllusiveC4** [comment]
Share your config file that refuses to load. It's likely a config syntax error.
