### ISSUE TITLE
[Suggestion] Make mob-drops only drop if killed by player 

### ISSUE THREAD

**Issue by GeorgeOrwell1** [TheIllusiveC4/Champions#91]
This would balance the mod as there wouldn't lay OP enchanted books everywhere every time a mob dies because of for example daylight.

**Comment by TheIllusiveC4** [comment]
This is already the behavior. As you can see in the [loot table](https://github.com/TheIllusiveC4/Champions/blob/1.16.x/src/main/resources/data/champions/loot_tables/champion_loot.json), the drops only occur if killed by a player.
