### ISSUE TITLE
Exception ticking world crash

### ISSUE THREAD

**Issue by InteJason** [TheIllusiveC4/Champions#92]
#### Versions (Be specific, do not write "latest"):
* Champions: 2.0.1.7
* Forge: 36.2.2

Crash when walking to a specific area, the crash report mentions the champions mod.
https://pastebin.com/n19juW4j

**Comment by TheIllusiveC4** [comment]
Hmm, it seems like the config didn't load correctly. Did you recently change anything about the configs before that happened? Or changed it at all?

**Comment by cebehs** [comment]
No, the config was never changed or modified in anyway. Although I would like to point out that this error is specific to the modpack: Mineshafts & Monsters Version 1.6.2. As I'm playing a different modpack with similar set of mods, and everything runs perfectly fine.
